// Datos seed portados desde el mock (assets/app.js)
export const data = {
  "mechanics": [
    "Taller Patagonia",
    "MotorSur",
    "Bariloche Diesel"
  ],
  "stores": [
    "Repuestos Centro",
    "Andina Parts",
    "Patagonia Frenos"
  ],
  "brands": [
    "Alfa Romeo",
    "Audi",
    "BMW",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Dodge",
    "Fiat",
    "Ford",
    "Honda",
    "Hyundai",
    "Jeep",
    "Kia",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Peugeot",
    "Ram",
    "Renault",
    "Seat",
    "Suzuki",
    "Toyota",
    "Volkswagen",
    "Otro"
  ],
  "models": {
    "Alfa Romeo": [
      "145",
      "146",
      "147",
      "155",
      "156",
      "159",
      "164",
      "166",
      "GT",
      "GTV",
      "Spider",
      "Brera",
      "MiTo",
      "Giulietta",
      "Giulia",
      "Stelvio",
      "4C",
      "8C Competizione",
      "Tonale"
    ],
    "Audi": [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "S3",
      "S4",
      "S5",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS Q3",
      "e-tron",
      "e-tron GT"
    ],
    "BMW": [
      "Serie 1",
      "Serie 2",
      "Serie 3",
      "Serie 4",
      "Serie 5",
      "Serie 6",
      "Serie 7",
      "Serie 8",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z3",
      "Z4",
      "Z8",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "i3",
      "i4",
      "iX",
      "iX1",
      "iX3"
    ],
    "Chery": [
      "QQ",
      "Face",
      "Fulwin",
      "Cielo",
      "A1",
      "A3",
      "A5",
      "Celer",
      "Tiggo",
      "Tiggo 2",
      "Tiggo 2 Pro",
      "Tiggo 3",
      "Tiggo 4",
      "Tiggo 4 Pro",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 7 Pro",
      "Tiggo 8",
      "Tiggo 8 Pro",
      "Arrizo 5",
      "Arrizo 6"
    ],
    "Chevrolet": [
      "Corsa",
      "Corsa Classic",
      "Classic",
      "Celta",
      "Prisma",
      "Kadett",
      "Astra",
      "Vectra",
      "Omega",
      "Calibra",
      "Cobalt",
      "Onix",
      "Onix Plus",
      "Aveo",
      "Sonic",
      "Cruze",
      "Malibu",
      "Camaro",
      "Agile",
      "Spin",
      "Meriva",
      "Zafira",
      "Montana",
      "Combo",
      "S10",
      "D-20",
      "Silverado",
      "Blazer",
      "TrailBlazer",
      "Tracker",
      "Captiva",
      "Equinox",
      "Grand Blazer",
      "Tahoe",
      "Suburban",
      "Vivant",
      "Bonanza"
    ],
    "Chrysler": [
      "Neon",
      "Stratus",
      "Cirrus",
      "Sebring",
      "300C",
      "300M",
      "PT Cruiser",
      "Town & Country",
      "Grand Caravan",
      "Voyager",
      "Caravan",
      "Crossfire"
    ],
    "Citroën": [
      "AX",
      "Saxo",
      "ZX",
      "Xantia",
      "Xsara",
      "Xsara Picasso",
      "Evasion",
      "Berlingo",
      "C2",
      "C3",
      "C3 Picasso",
      "C3 Aircross",
      "C4",
      "C4 Picasso",
      "Grand C4 Picasso",
      "C4 Lounge",
      "C4 Cactus",
      "C4 Aircross",
      "C5",
      "C5 Aircross",
      "C6",
      "C8",
      "Jumpy",
      "Jumper",
      "DS3",
      "DS4",
      "DS5"
    ],
    "Dodge": [
      "Neon",
      "Stratus",
      "Caliber",
      "Avenger",
      "Journey",
      "Dakota",
      "Durango",
      "Grand Caravan",
      "Ram 1500",
      "Charger",
      "Challenger",
      "Viper"
    ],
    "Fiat": [
      "147",
      "Uno",
      "Duna",
      "Fiorino",
      "Tipo",
      "Tempra",
      "Marea",
      "Palio",
      "Palio Weekend",
      "Siena",
      "Albea",
      "Idea",
      "Punto",
      "Grande Punto",
      "Linea",
      "Bravo",
      "Brava",
      "Stilo",
      "Strada",
      "Doblo",
      "Ducato",
      "Scudo",
      "Qubo",
      "Multipla",
      "Sedici",
      "Freemont",
      "500",
      "500L",
      "500X",
      "Mobi",
      "Argo",
      "Cronos",
      "Toro",
      "Pulse",
      "Fastback",
      "Coupe",
      "Barchetta"
    ],
    "Ford": [
      "Escort",
      "Orion",
      "Sierra",
      "Fiesta",
      "Ka",
      "Ka+",
      "Focus",
      "Mondeo",
      "Fusion",
      "EcoSport",
      "Kuga",
      "Edge",
      "Escape",
      "Explorer",
      "Territory",
      "Bronco",
      "Bronco Sport",
      "Ranger",
      "Ranger Raptor",
      "Courier",
      "Transit",
      "F-100",
      "F-150",
      "F-250",
      "F-1000",
      "Maverick",
      "Mustang",
      "Galaxy"
    ],
    "Honda": [
      "Civic",
      "City",
      "Fit",
      "Accord",
      "CR-V",
      "HR-V",
      "WR-V",
      "Pilot",
      "Odyssey",
      "CR-Z",
      "Legend",
      "Prelude",
      "Integra",
      "S2000"
    ],
    "Hyundai": [
      "Atos",
      "Excel",
      "Accent",
      "Elantra",
      "Sonata",
      "Azera",
      "Getz",
      "i10",
      "Grand i10",
      "i20",
      "i30",
      "HB20",
      "HB20S",
      "Veloster",
      "Tiburon",
      "Coupe",
      "Genesis",
      "Tucson",
      "ix35",
      "Santa Fe",
      "Grand Santa Fe",
      "Creta",
      "Kona",
      "Veracruz",
      "Terracan",
      "Galloper",
      "Santamo",
      "H1",
      "H100",
      "Starex",
      "Porter"
    ],
    "Jeep": [
      "Cherokee",
      "Grand Cherokee",
      "Wrangler",
      "Compass",
      "Renegade",
      "Commander",
      "Patriot",
      "Liberty",
      "Gladiator"
    ],
    "Kia": [
      "Rio",
      "Picanto",
      "Sephia",
      "Clarus",
      "Cerato",
      "Cerato Forte",
      "Magentis",
      "Optima",
      "Carens",
      "Carnival",
      "Grand Carnival",
      "Soul",
      "Sportage",
      "Sorento",
      "Mohave",
      "Seltos",
      "Stonic",
      "Niro",
      "Stinger",
      "Pregio",
      "Bongo",
      "Besta"
    ],
    "Mercedes-Benz": [
      "Clase A",
      "Clase B",
      "Clase C",
      "Clase E",
      "Clase S",
      "CLA",
      "CLK",
      "CLS",
      "SLK",
      "SL",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLK",
      "GLS",
      "ML",
      "GL",
      "Clase G",
      "Clase R",
      "Clase V",
      "Vito",
      "Viano",
      "Sprinter",
      "Citan",
      "190"
    ],
    "Mitsubishi": [
      "Lancer",
      "Lancer Evolution",
      "Mirage",
      "Colt",
      "Galant",
      "Eclipse",
      "Eclipse Cross",
      "3000GT",
      "ASX",
      "Outlander",
      "Montero",
      "Montero Sport",
      "Pajero",
      "Pajero Sport",
      "Pajero Dakar",
      "Nativa",
      "L200",
      "Triton",
      "Space Wagon",
      "Space Star",
      "Grandis",
      "Endeavor"
    ],
    "Nissan": [
      "Sentra",
      "Almera",
      "Tiida",
      "Versa",
      "Note",
      "March",
      "Micra",
      "Primera",
      "Maxima",
      "Altima",
      "Pathfinder",
      "Murano",
      "X-Trail",
      "Qashqai",
      "Kicks",
      "Juke",
      "Terrano",
      "Frontier",
      "NP300",
      "Navara",
      "Pickup",
      "Patrol",
      "Xterra",
      "350Z",
      "370Z",
      "GT-R",
      "Livina",
      "Platina",
      "Tsuru",
      "Urvan",
      "NV200"
    ],
    "Peugeot": [
      "106",
      "205",
      "206",
      "206 CC",
      "207",
      "207 Compact",
      "208",
      "2008",
      "306",
      "307",
      "307 CC",
      "308",
      "3008",
      "405",
      "406",
      "407",
      "408",
      "5008",
      "504",
      "505",
      "605",
      "607",
      "301",
      "508",
      "RCZ",
      "Partner",
      "Expert",
      "Boxer",
      "Rifter",
      "Traveller",
      "Hoggar"
    ],
    "Ram": [
      "700",
      "1000",
      "1200",
      "1500",
      "2500",
      "3500",
      "Rampage",
      "ProMaster",
      "Dakota"
    ],
    "Renault": [
      "9",
      "11",
      "12",
      "18",
      "19",
      "21",
      "Clio",
      "Clio Mio",
      "Twingo",
      "Megane",
      "Megane RS",
      "Scenic",
      "Grand Scenic",
      "Laguna",
      "Safrane",
      "Symbol",
      "Logan",
      "Sandero",
      "Sandero RS",
      "Stepway",
      "Fluence",
      "Latitude",
      "Kangoo",
      "Express",
      "Trafic",
      "Master",
      "Duster",
      "Oroch",
      "Captur",
      "Koleos",
      "Kwid",
      "Alaskan"
    ],
    "Seat": [
      "Ibiza",
      "Cordoba",
      "Cordoba Vario",
      "Leon",
      "Toledo",
      "Altea",
      "Alhambra",
      "Arosa",
      "Inca",
      "Malaga"
    ],
    "Suzuki": [
      "Fun",
      "Maruti",
      "Swift",
      "Baleno",
      "Celerio",
      "Alto",
      "SX4",
      "S-Cross",
      "Vitara",
      "Grand Vitara",
      "Grand Nomade",
      "Jimny",
      "Samurai",
      "Sidekick",
      "Ignis",
      "Kizashi",
      "Liana",
      "Aerio",
      "APV",
      "Carry",
      "Super Carry",
      "Fun Truck"
    ],
    "Toyota": [
      "Corolla",
      "Corolla Cross",
      "Etios",
      "Yaris",
      "Camry",
      "Avensis",
      "Corona",
      "Tercel",
      "Paseo",
      "Celica",
      "Supra",
      "86",
      "GR86",
      "GR Yaris",
      "Prius",
      "RAV4",
      "C-HR",
      "SW4",
      "4Runner",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Hilux",
      "Hiace",
      "Innova",
      "FJ Cruiser",
      "Previa",
      "Spacio"
    ],
    "Volkswagen": [
      "1500",
      "Gol",
      "Gol Country",
      "Gol Trend",
      "Senda",
      "Saveiro",
      "Polo",
      "Polo Classic",
      "Polo Track",
      "Virtus",
      "Voyage",
      "Parati",
      "Bora",
      "Vento",
      "Jetta",
      "Golf",
      "Passat",
      "CC",
      "Suran",
      "SpaceFox",
      "CrossFox",
      "Fox",
      "Up",
      "Nivus",
      "T-Cross",
      "Taos",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "Amarok",
      "Caddy",
      "Transporter",
      "Crafter",
      "Sharan",
      "Scirocco",
      "New Beetle",
      "Beetle",
      "Eos"
    ],
    "Otro": []
  },
  "categories": [
    {
      "id": "accesorios",
      "label": "Accesorios y equipamiento",
      "icon": "fa-toolbox"
    },
    {
      "id": "carroceria",
      "label": "Carrocería",
      "icon": "fa-car-side"
    },
    {
      "id": "electricidad",
      "label": "Electricidad y electrónica",
      "icon": "fa-bolt"
    },
    {
      "id": "embrague",
      "label": "Embrague y transmisión",
      "icon": "fa-gears"
    },
    {
      "id": "frenos",
      "label": "Frenos",
      "icon": "fa-record-vinyl"
    },
    {
      "id": "inyeccion",
      "label": "Inyección y combustible",
      "icon": "fa-gas-pump"
    },
    {
      "id": "lubricacion",
      "label": "Lubricentro",
      "icon": "fa-oil-can"
    },
    {
      "id": "motor",
      "label": "Motor",
      "icon": "fa-gear"
    },
    {
      "id": "refrigeracion",
      "label": "Refrigeración A/C Calefa",
      "icon": "fa-snowflake"
    },
    {
      "id": "suspension",
      "label": "Suspensión y dirección",
      "icon": "fa-car-burst"
    }
  ],
  "quotePool": [
    {
      "alias": "Proveedor #12",
      "zone": "Centro",
      "rating": 4.9,
      "partBrand": "Bosch",
      "price": 48500,
      "warranty": "6 meses",
      "real": {
        "name": "Repuestos Centro",
        "phone": "+54 9 294 4123-456",
        "address": "Av. Bustillo 1240, Bariloche"
      }
    },
    {
      "alias": "Distribuidor Centro",
      "zone": "Centro",
      "rating": 4.7,
      "partBrand": "TRW",
      "price": 44900,
      "warranty": "3 meses",
      "real": {
        "name": "Andina Parts",
        "phone": "+54 9 294 4567-890",
        "address": "Onelli 530, Bariloche"
      }
    },
    {
      "alias": "Zona Oeste Parts",
      "zone": "Oeste",
      "rating": 4.8,
      "partBrand": "Ferodo",
      "price": 39900,
      "warranty": "12 meses",
      "real": {
        "name": "Patagonia Frenos",
        "phone": "+54 9 294 4789-012",
        "address": "Km 5 Av. Bustillo, Bariloche"
      }
    },
    {
      "alias": "AutoPartes Sur",
      "zone": "Sur",
      "rating": 4.6,
      "partBrand": "Fras-le",
      "price": 37500,
      "warranty": "6 meses",
      "real": {
        "name": "Sur Repuestos",
        "phone": "+54 9 294 4222-333",
        "address": "Elordi 870, Bariloche"
      }
    }
  ],
  "ads": [
    {
      "store": "Repuestos Centro",
      "discount": "20% OFF",
      "icon": "fa-record-vinyl",
      "color": "linear-gradient(135deg,#6D28D9,#8B5CF6)",
      "phone": "5492944123456"
    },
    {
      "store": "Andina Parts",
      "discount": "15% OFF",
      "icon": "fa-oil-can",
      "color": "linear-gradient(135deg,#EAB308,#FACC15)",
      "phone": "5492944567890"
    },
    {
      "store": "Lubricentro Andino",
      "discount": "2x1 filtros",
      "icon": "fa-gear",
      "color": "linear-gradient(135deg,#22C55E,#16A34A)",
      "phone": "5492944333222"
    }
  ]
};
